CREATE DATABASE QuanLyCanHo
GO

USE QuanLyCanHo
GO

/*TABLE AREA*/
--TABLE INCLUDES ACCOUNT INFORMATION
CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50)
)
GO

--TABLE INCLUDES APARTMENT INFORMATION
CREATE TABLE APARTMENT_INFO
(
	STT INT IDENTITY,
	TENCHUHO VARCHAR(40),
	MACANHO VARCHAR(25),
	DUAN VARCHAR(50),
	TINHTRANG NVARCHAR(100),
	MASOTHUE VARCHAR(25),
	HINHTHUCKHAITHUE VARCHAR(50),
	COQUANTHUTHUE VARCHAR(50),
	THUE FLOAT,
	PHIKEKHAITHUE FLOAT,
	PHIQUANLY FLOAT,
	TIENREFUNDKHACH FLOAT,
	TIENTHU FLOAT,
	PHIDONVESINH FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	SONGAYNHACNHO INT,
	CHUKY INT
)
GO

--TABLE INCLUDES APARTMENT NEED TO PAY MONEY FOR ITS TAX
CREATE TABLE APARTMENT_MONEY
(
	STT INT IDENTITY,
	TENCHUHO VARCHAR(40),
	MACANHO VARCHAR(25),
	NGAYDAU DATE,
	NGAYCUOI DATE,
	CHUKY INT,
	TIENCANTHU FLOAT,
	TRANGTHAI VARCHAR(30) DEFAULT 'Chua thu tien',
)
GO

--TABLE INCLUDES APARTMENT NEED TO REMIND TO HAVE NEW CONTRACT OR NOT
CREATE TABLE APARTMENT_REMIND
(
	STT INT IDENTITY,
	TENCHUHO VARCHAR(40),
	MACANHO VARCHAR(25),
	DUAN VARCHAR(50),
	TINHTRANG NVARCHAR(100),
	MASOTHUE VARCHAR(25),
	HINHTHUCKHAITHUE VARCHAR(50),
	COQUANTHUTHUE VARCHAR(50),
	TIENTHU FLOAT,
	PHIDONVESINH FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	SONGAYNHACNHO INT,
	CHUKY INT
)
GO

--TABLE INCLUDES INFORMATION OF EXPIRED APARTMENT
CREATE TABLE EXPIRED_APARTMENT
(
	STT INT IDENTITY,
	MACANHO VARCHAR(25),
	TENCHUHO VARCHAR(40),
	MASOTHUE VARCHAR(25),
	HINHTHUCKHAITHUE VARCHAR(50),
	COQUANTHUTHUE VARCHAR(50),
	TIENTHU FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	CHUKY INT
)
GO

/*PROC AREA*/
-- PROC FOR LOGIN
CREATE PROC Login
@userName VARCHAR(50), @passWord VARCHAR(50)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND PASSWORD = @passWord
END
GO

--PROC FOR DELETING INFORMATION OF APARMENT IN APARTMENTINFO AND APARTMENTMONEY
CREATE PROC DELETING_APARTMENT
@macanho VARCHAR(25)
AS
BEGIN
	DELETE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_MONEY WHERE MACANHO = @macanho
END
GO

--PROC FOR ADDING EXPIRED APARTMENT AND DELETING INFO IN APARTMENT_INFO
CREATE PROC ADDING_EXPIRED_APARTMENT
@macanho VARCHAR(25)
AS
BEGIN
	DECLARE @tenchuho VARCHAR(40)
	DECLARE @masothue VARCHAR(25)
	DECLARE @hinhthuckhaithue VARCHAR(50)
	DECLARE @coquanthuthue VARCHAR(50)
	DECLARE @tienthu FLOAT
	DECLARE @ngaybatdau DATE
	DECLARE @ngayketthuc DATE
	DECLARE @chuky INT

	SELECT @tenchuho = TENCHUHO FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @masothue = MASOTHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @hinhthuckhaithue = HINHTHUCKHAITHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @coquanthuthue = COQUANTHUTHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @tienthu = TIENTHU FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @ngaybatdau = NGAYBATDAU FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @ngayketthuc = NGAYKETTHUC FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @chuky = CHUKY FROM APARTMENT_INFO WHERE MACANHO = @macanho

	INSERT INTO EXPIRED_APARTMENT(MACANHO,TENCHUHO,MASOTHUE,HINHTHUCKHAITHUE,COQUANTHUTHUE,TIENTHU,NGAYBATDAU,NGAYKETTHUC,CHUKY)
	VALUES(@macanho,@tenchuho,@masothue,@hinhthuckhaithue,@coquanthuthue,@tienthu,@ngaybatdau,@ngayketthuc,@chuky)

	DELETE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_MONEY	 WHERE MACANHO = @macanho
END
GO

--PROC FOR NEXT CYCLING NGAYCANTHU FOR APARTMENT_MONEY
CREATE PROC Next_Ngaycanthu
@macanho VARCHAR(25)
AS
BEGIN
	
	DECLARE @chuky INT
	DECLARE @ngaydau DATE
	DECLARE @ngaycuoi DATE
	DECLARE @ngaydauNext DATE
	DECLARE @ngaycuoiNext DATE

	SELECT @chuky =  CHUKY FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	SELECT @ngaydau = NGAYDAU FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	SELECT @ngaycuoi = NGAYCUOI FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	
	SET @ngaydauNext = DATEADD(DAY, 1 , @ngaycuoi)
	SET @ngaycuoiNext = DATEADD(MONTH, @chuky , @ngaycuoi)

	UPDATE APARTMENT_MONEY
	SET NGAYDAU = @ngaydauNext, NGAYCUOI = @ngaycuoiNext, TRANGTHAI = 'Chua thu tien'
	WHERE MACANHO = @macanho

END
GO

CREATE PROC Add_RemindApart
AS
BEGIN
	DECLARE @songaynhacnho INT
	DECLARE @isremind VARCHAR(10)
	

	SELECT @songaynhacnho = SONGAYNHACNHO FROM APARTMENT_INFO
END

/*TRIGGER AREA*/
--TRIGGER FOR ADDING INFORMATION FOR APARTMENT MONEY
CREATE TRIGGER Adding
ON APARTMENT_INFO
FOR INSERT
AS
BEGIN
	DECLARE @macanho VARCHAR(25)
	DECLARE @tenchuho VARCHAR(40)
	DECLARE @ngaycanthu DATE
	DECLARE @chuky INT
	DECLARE @ngaydau DATE
	DECLARE @ngaycuoi DATE
	DECLARE @ngaycuoiMinus DATE
	DECLARE @tienthu FLOAT
	DECLARE @tiencanthu FLOAT


	SELECT @macanho = MACANHO FROM inserted
	SELECT @tenchuho = TENCHUHO FROM inserted
	SELECT @ngaydau = NGAYBATDAU FROM inserted
	SELECT @chuky = CHUKY FROM inserted
	SELECT @tienthu = TIENTHU FROM inserted

	SET @ngaycuoi = DATEADD(MONTH, @chuky, @ngaydau)
	SET @ngaycuoiMinus = DATEADD(DAY, -1, @ngaycuoi)
	SET @tiencanthu = @tienthu

	INSERT INTO APARTMENT_MONEY(MACANHO, TENCHUHO, NGAYDAU, NGAYCUOI, CHUKY, TIENCANTHU) VALUES(@macanho, @tenchuho, @ngaydau, @ngaycuoiMinus, @chuky, @tiencanthu)
END
GO

/*DEFAULT AREA*/
--CREATE DEFAULT ACCOUNT FOR PROGRAM
INSERT INTO ACCOUNT(USERNAME,PASSWORD) VALUES('admin1','123456')
GO