CREATE DATABASE QuanLyCanHo
GO

USE QuanLyCanHo
GO

/*TABLE AREA*/
--TABLE INCLUDES ACCOUNT INFORMATION
CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50)
)
GO

--TABLE INCLUDES APARTMENT INFORMATION
CREATE TABLE APARTMENT_INFO
(
	STT INT IDENTITY,
	TENCHUHO NVARCHAR(40),
	MACANHO NVARCHAR(25),
	DUAN NVARCHAR(50),
	TINHTRANG NVARCHAR(100),
	MASOTHUE NVARCHAR(25),
	HINHTHUCKHAITHUE NVARCHAR(50),
	COQUANTHUTHUE NVARCHAR(50),
	THUE FLOAT,
	PHIKEKHAITHUE FLOAT,
	PHIQUANLY FLOAT,
	TIENREFUNDKHACH FLOAT,
	TIENTHU FLOAT,
	PHIDONVESINH FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	SONGAYNHACNHO INT,
	CHUKY INT
)
GO

--TABLE INCLUDES APARTMENT NEED TO PAY MONEY FOR ITS TAX
CREATE TABLE APARTMENT_MONEY
(
	STT INT IDENTITY,
	TENCHUHO NVARCHAR(40),
	MACANHO NVARCHAR(25),
	NGAYDAU DATE,
	NGAYCUOI DATE,
	CHUKY INT,
	TIENCANTHU FLOAT,
	TRANGTHAI NVARCHAR(30) DEFAULT 'Chua thu tien',
)
GO

--TABLE INCLUDES APARTMENT NEED TO NEGOTIATE ABOUT CONTRACT
CREATE TABLE APARTMENT_CONTRACT
(
	STT INT IDENTITY,
	TENCHUHO NVARCHAR(40),
	MACANHO NVARCHAR(25),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	NGAYNHAC DATE,
	CHUKY INT,
	SONGAYNHACNHO INT,
	TIENTHU FLOAT,
	STATUS NVARCHAR(20) DEFAULT 'NOT DONE'
)
GO


--TABLE INCLUDES INFORMATION OF EXPIRED APARTMENT
CREATE TABLE EXPIRED_APARTMENT
(
	STT INT IDENTITY,
	MACANHO NVARCHAR(25),
	TENCHUHO NVARCHAR(40),
	MASOTHUE NVARCHAR(25),
	HINHTHUCKHAITHUE NVARCHAR(50),
	COQUANTHUTHUE NVARCHAR(50),
	TIENTHU FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	CHUKY INT
)
GO

--TABLE INCLUDES INFORMATION OF APARTMENT_FINANCE
CREATE TABLE APARTMENT_FINANCE
(
	STT INT IDENTITY,
	MACANHO NVARCHAR(25),
	THUE FLOAT,
	PHIKEKHAITHUE FLOAT,
	PHIQUANLY FLOAT,
	TIENREFUNDKHACH FLOAT,
	PHIDONVESINH FLOAT,
	TIENTHU FLOAT,
	STATUS_THUE NVARCHAR(20) DEFAULT 'UNCHECKED',
	STATUS_PHIKEKHAITHUE NVARCHAR(20) DEFAULT 'UNCHECKED',
	STATUS_PHIQUANLY NVARCHAR(20) DEFAULT 'UNCHECKED',
	STATUS_TIENREFUNDKHACH NVARCHAR(20) DEFAULT 'UNCHECKED',
	STATUS_PHIDONVESINH NVARCHAR(20) DEFAULT 'UNCHECKED',
	STATUS_TIENTHU NVARCHAR(20) DEFAULT 'UNCHECKED'
)
GO

/*PROC AREA*/
-- PROC FOR LOGIN
CREATE PROC Login
@userName NVARCHAR(50), @passWord NVARCHAR(50)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND PASSWORD = @passWord
END
GO

--PROC FOR DELETING INFORMATION OF APARMENT IN APARTMENTINFO AND APARTMENTMONEY
CREATE PROC DELETING_APARTMENT
@macanho NVARCHAR(25)
AS
BEGIN
	DELETE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_CONTRACT WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_FINANCE WHERE MACANHO = @macanho
END
GO

--PROC FOR ADDING EXPIRED APARTMENT AND DELETING INFO IN APARTMENT_INFO
CREATE PROC ADDING_EXPIRED_APARTMENT
@macanho NVARCHAR(25)
AS
BEGIN
	DECLARE @tenchuho NVARCHAR(40)
	DECLARE @masothue NVARCHAR(25)
	DECLARE @hinhthuckhaithue NVARCHAR(50)
	DECLARE @coquanthuthue NVARCHAR(50)
	DECLARE @tienthu FLOAT
	DECLARE @ngaybatdau DATE
	DECLARE @ngayketthuc DATE
	DECLARE @chuky INT

	SELECT @tenchuho = TENCHUHO FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @masothue = MASOTHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @hinhthuckhaithue = HINHTHUCKHAITHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @coquanthuthue = COQUANTHUTHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @tienthu = TIENTHU FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @ngaybatdau = NGAYBATDAU FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @ngayketthuc = NGAYKETTHUC FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @chuky = CHUKY FROM APARTMENT_INFO WHERE MACANHO = @macanho

	INSERT INTO EXPIRED_APARTMENT(MACANHO,TENCHUHO,MASOTHUE,HINHTHUCKHAITHUE,COQUANTHUTHUE,TIENTHU,NGAYBATDAU,NGAYKETTHUC,CHUKY)
	VALUES(@macanho,@tenchuho,@masothue,@hinhthuckhaithue,@coquanthuthue,@tienthu,@ngaybatdau,@ngayketthuc,@chuky)

	DELETE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_MONEY	 WHERE MACANHO = @macanho
END
GO

--PROC FOR NEXT CYCLING NGAYCANTHU FOR APARTMENT_MONEY
CREATE PROC Next_Ngaycanthu
@macanho NVARCHAR(25)
AS
BEGIN
	
	DECLARE @chuky INT
	DECLARE @ngaydau DATE
	DECLARE @ngaycuoi DATE
	DECLARE @ngaydauNext DATE
	DECLARE @ngaycuoiNext DATE

	SELECT @chuky =  CHUKY FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	SELECT @ngaydau = NGAYDAU FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	SELECT @ngaycuoi = NGAYCUOI FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	
	SET @ngaydauNext = DATEADD(DAY, 1 , @ngaycuoi)
	SET @ngaycuoiNext = DATEADD(MONTH, @chuky , @ngaycuoi)

	UPDATE APARTMENT_MONEY
	SET NGAYDAU = @ngaydauNext, NGAYCUOI = @ngaycuoiNext, TRANGTHAI = 'Chua thu tien'
	WHERE MACANHO = @macanho

	UPDATE APARTMENT_FINANCE
	SET STATUS_THUE = 'UNCHECKED', STATUS_PHIKEKHAITHUE = 'UNCHECKED', STATUS_PHIQUANLY= 'UNCHECKED', 
		STATUS_TIENREFUNDKHACH = 'UNCHECKED', STATUS_PHIDONVESINH = 'UNCHECKED', STATUS_TIENTHU  = 'UNCHECKED'
	WHERE MACANHO = @macanho

END
GO

/*TRIGGER AREA*/
--TRIGGER FOR ADDING INFORMATION FOR APARTMENT MONEY
CREATE TRIGGER ADDING_APARTMENT_MONEY
ON APARTMENT_INFO
FOR INSERT
AS
BEGIN
	DECLARE @macanho NVARCHAR(25)
	DECLARE @tenchuho NVARCHAR(40)
	DECLARE @ngaycanthu DATE
	DECLARE @chuky INT
	DECLARE @ngaydau DATE
	DECLARE @ngaycuoi DATE
	DECLARE @ngaycuoiMinus DATE
	DECLARE @tienthu FLOAT
	DECLARE @tiencanthu FLOAT


	SELECT @macanho = MACANHO FROM inserted
	SELECT @tenchuho = TENCHUHO FROM inserted
	SELECT @ngaydau = NGAYBATDAU FROM inserted
	SELECT @chuky = CHUKY FROM inserted
	SELECT @tienthu = TIENTHU FROM inserted

	SET @ngaycuoi = DATEADD(MONTH, @chuky, @ngaydau)
	SET @ngaycuoiMinus = DATEADD(DAY, -1, @ngaycuoi)
	SET @tiencanthu = @tienthu

	INSERT INTO APARTMENT_MONEY(MACANHO, TENCHUHO, NGAYDAU, NGAYCUOI, CHUKY, TIENCANTHU) VALUES(@macanho, @tenchuho, @ngaydau, @ngaycuoiMinus, @chuky, @tiencanthu)
END
GO

--TRIGGER FOR ADDING INFORMATION FOR APARTMENT_CONTRACT
CREATE TRIGGER ADDING_APARTMENT_CONTRACT
ON APARTMENT_INFO
FOR INSERT
AS
BEGIN
	DECLARE @macanho NVARCHAR(25)
	DECLARE @tenchuho NVARCHAR(40)
	DECLARE @chuky INT
	DECLARE @ngaybatdau DATE
	DECLARE @ngayketthuc DATE
	DECLARE @songaynhacnho INT
	DECLARE @tienthu FLOAT
	DECLARE @ngaynhac DATE

	SELECT @macanho = MACANHO FROM inserted
	SELECT @tenchuho = TENCHUHO FROM inserted
	SELECT @ngaybatdau = NGAYBATDAU FROM inserted
	SELECT @ngayketthuc = NGAYKETTHUC FROM inserted
	SELECT @songaynhacnho = SONGAYNHACNHO FROM inserted
	SELECT @chuky = CHUKY FROM inserted
	SELECT @tienthu = TIENTHU FROM inserted

	SET @ngaynhac = DATEADD(DAY, -@songaynhacnho, @ngayketthuc)

	INSERT INTO APARTMENT_CONTRACT(MACANHO, TENCHUHO, NGAYBATDAU, NGAYKETTHUC, NGAYNHAC, CHUKY, SONGAYNHACNHO, TIENTHU) 
	VALUES(@macanho, @tenchuho, @ngaybatdau, @ngayketthuc, @ngaynhac, @chuky, @songaynhacnho, @tienthu)
END
GO

--TRIGGER FOR ADDING INFORMATION FOR APARTMENT_FINANCE
CREATE TRIGGER ADDING_APARTMENT_FINANCE
ON APARTMENT_INFO
FOR INSERT
AS
BEGIN

	DECLARE @macanho NVARCHAR(25)
	DECLARE @thue FLOAT
	DECLARE @phikekhaithue FLOAT
	DECLARE @phiquanly FLOAT
	DECLARE @tienrefundkhach FLOAT
	DECLARE @phidonvesinh FLOAT
	DECLARE @tienthu FLOAT

	SELECT @macanho = MACANHO FROM inserted
	SELECT @thue = THUE FROM inserted
	SELECT @phikekhaithue = PHIKEKHAITHUE FROM inserted
	SELECT @phiquanly = PHIQUANLY FROM inserted
	SELECT @tienrefundkhach = TIENREFUNDKHACH FROM inserted
	SELECT @phidonvesinh = PHIDONVESINH FROM inserted
	SELECT @tienthu = TIENTHU FROM inserted

	INSERT INTO APARTMENT_FINANCE(MACANHO, THUE, PHIKEKHAITHUE, PHIQUANLY, TIENREFUNDKHACH, PHIDONVESINH, TIENTHU) 
	VALUES(@macanho, @thue, @phikekhaithue, @phiquanly, @tienrefundkhach, @phidonvesinh, @tienthu)

END
GO

/*DEFAULT AREA*/
--CREATE DEFAULT ACCOUNT FOR PROGRAM
INSERT INTO ACCOUNT(USERNAME,PASSWORD) VALUES('admin1','123456')
GO