CREATE DATABASE QuanLyCanHo
GO

USE QuanLyCanHo
GO

/*TABLE AREA*/
--TABLE INCLUDES ACCOUNT INFORMATION
CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50)
)
GO

--TABLE INCLUDES APARTMENT INFORMATION
CREATE TABLE APARTMENT_INFO
(
	STT INT IDENTITY,
	MACANHO VARCHAR(25),
	TENCHUHO VARCHAR(40),
	MASOTHUE VARCHAR(25),
	HINHTHUCKHAITHUE VARCHAR(50),
	COQUANTHUTHUE VARCHAR(50),
	TIENTHU FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	CHUKY INT
)
GO

--TABLE INCLUDES APARTMENT NEED TO PAY MONEY FOR ITS TAX
CREATE TABLE APARTMENT_MONEY
(
	STT INT IDENTITY,
	TENCHUHO VARCHAR(40),
	MACANHO VARCHAR(25),
	NGAYCANTHU DATE,
	CHUKY INT,
	TIENCANTHU FLOAT,
	TRANGTHAI VARCHAR(30) DEFAULT 'Chua thu tien',
)
GO

--TABLE INCLUDES INFORMATION OF EXPIRED APARTMENT
CREATE TABLE EXPIRED_APARTMENT
(
	STT INT IDENTITY,
	MACANHO VARCHAR(25),
	TENCHUHO VARCHAR(40),
	MASOTHUE VARCHAR(25),
	HINHTHUCKHAITHUE VARCHAR(50),
	COQUANTHUTHUE VARCHAR(50),
	TIENTHU FLOAT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	CHUKY INT
)
GO

/*PROC AREA*/
-- PROC FOR LOGIN
CREATE PROC Login
@userName VARCHAR(50), @passWord VARCHAR(50)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND PASSWORD = @passWord
END
GO

--PROC FOR DELETING INFORMATION OF APARMENT IN APARTMENTINFO AND APARTMENTMONEY
CREATE PROC DELETING_APARTMENT
@macanho VARCHAR(25)
AS
BEGIN
	DELETE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	DELETE FROM APARTMENT_MONEY WHERE MACANHO = @macanho
END
GO

--PROC FOR ADDING EXPIRED APARTMENT AND DELETING INFO IN APARTMENT_INFO
CREATE PROC ADDING_EXPIRED_APARTMENT
@macanho VARCHAR(25)
AS
BEGIN
	DECLARE @tenchuho VARCHAR(40)
	DECLARE @masothue VARCHAR(25)
	DECLARE @hinhthuckhaithue VARCHAR(50)
	DECLARE @coquanthuthue VARCHAR(50)
	DECLARE @tienthu FLOAT
	DECLARE @ngaybatdau DATE
	DECLARE @ngayketthuc DATE
	DECLARE @chuky INT

	SELECT @tenchuho = TENCHUHO FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @masothue = MASOTHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @hinhthuckhaithue = HINHTHUCKHAITHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @coquanthuthue = COQUANTHUTHUE FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @tienthu = TIENTHU FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @ngaybatdau = NGAYBATDAU FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @ngayketthuc = NGAYKETTHUC FROM APARTMENT_INFO WHERE MACANHO = @macanho
	SELECT @chuky = CHUKY FROM APARTMENT_INFO WHERE MACANHO = @macanho

	INSERT INTO EXPIRED_APARTMENT(MACANHO,TENCHUHO,MASOTHUE,HINHTHUCKHAITHUE,COQUANTHUTHUE,TIENTHU,NGAYBATDAU,NGAYKETTHUC,CHUKY)
	VALUES(@macanho,@tenchuho,@masothue,@hinhthuckhaithue,@coquanthuthue,@tienthu,@ngaybatdau,@ngayketthuc,@chuky)

	DELETE FROM APARTMENT_INFO WHERE MACANHO = @macanho

END
GO

--PROC FOR NEXT CYCLING NGAYCANTHU FOR APARTMENT_MONEY
CREATE PROC Next_Ngaycanthu
@macanho VARCHAR(25)
AS
BEGIN
	
	DECLARE @chuky INT
	DECLARE @ngayketthuc DATE
	DECLARE @ngaycanthu DATE
	DECLARE @ngaycanthuNext DATE
	DECLARE @ngaycanthuNextCycle DATE

	SELECT @chuky =  CHUKY FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	SELECT @ngaycanthu = NGAYCANTHU FROM APARTMENT_MONEY WHERE MACANHO = @macanho
	SELECT @ngayketthuc = NGAYKETTHUC FROM APARTMENT_INFO WHERE MACANHO = @macanho
	
	IF (@ngaycanthu < @ngayketthuc)
		BEGIN
			IF (DAY(@ngaycanthu) = 1)
				BEGIN
					SET @ngaycanthuNext = DATEADD(DAY, -1 , @ngaycanthu)
					SET @ngaycanthuNextCycle = DATEADD(MONTH, @chuky, @ngaycanthuNext)
				END
			ELSE
				BEGIN
					SET @ngaycanthuNextCycle = DATEADD(MONTH, @chuky, @ngaycanthu)
				END

			UPDATE APARTMENT_MONEY
			SET NGAYCANTHU = @ngaycanthuNextCycle, TRANGTHAI = 'Chua thu tien'
			WHERE MACANHO = @macanho
		END

	ELSE
		BEGIN
			EXEC dbo.ADDING_EXPIRED_APARTMENT @macanho
			DELETE FROM APARTMENT_MONEY WHERE MACANHO = @macanho
		END

END
GO

/*TRIGGER AREA*/
--TRIGGER FOR ADDING INFORMATION FOR APARTMENT MONEY
CREATE TRIGGER Adding
ON APARTMENT_INFO
FOR INSERT
AS
BEGIN
	DECLARE @macanho VARCHAR(25)
	DECLARE @tenchuho VARCHAR(40)
	DECLARE @ngaycanthu DATE
	DECLARE @chuky INT
	DECLARE @ngaybatdau DATE
	DECLARE @ngaycanthuMinus DATE
	DECLARE @tienthu FLOAT
	DECLARE @tiencanthu FLOAT


	SELECT @macanho = MACANHO FROM inserted
	SELECT @tenchuho = TENCHUHO FROM inserted
	SELECT @ngaybatdau = NGAYBATDAU FROM inserted
	SELECT @chuky = CHUKY FROM inserted
	SELECT @tienthu = TIENTHU FROM inserted

	SET @ngaycanthu = DATEADD(MONTH, @chuky, @ngaybatdau)
	SET @ngaycanthuMinus = DATEADD(DAY, -1, @ngaycanthu)
	SET @tiencanthu = @tienthu * @chuky

	INSERT INTO APARTMENT_MONEY(MACANHO, TENCHUHO, NGAYCANTHU, CHUKY, TIENCANTHU) VALUES(@macanho, @tenchuho, @ngaycanthuMinus, @chuky, @tiencanthu)
END
GO

/*DEFAULT AREA*/
--CREATE DEFAULT ACCOUNT FOR PROGRAM
INSERT INTO ACCOUNT(USERNAME,PASSWORD) VALUES('admin1','123456')
GO

